import { COMPLAINT_STATUSES, SEVERITY_LEVELS, ISSUE_TYPES, LOCATIONS, OFFICERS, CAMERA_NAMES } from './types.js';

export const DUMMY_COMPLAINTS = [
  // Pending complaints (unassigned)
  {
    id: 'C001',
    date: '2026-06-24',
    time: '09:15 AM',
    location: LOCATIONS[0],
    issueType: ISSUE_TYPES.SAFETY_HAZARD,
    description: 'Debris on runway blocking traffic',
    severity: SEVERITY_LEVELS.CRITICAL,
    status: COMPLAINT_STATUSES.PENDING,
    assignedTo: null,
    cameraNumber: CAMERA_NAMES[0],
    createdAt: new Date('2026-06-24T09:15:00'),
  },
  {
    id: 'C002',
    date: '2026-06-24',
    time: '09:45 AM',
    location: LOCATIONS[1],
    issueType: ISSUE_TYPES.EQUIPMENT_MALFUNCTION,
    description: 'Landing gear indicator malfunctioning',
    severity: SEVERITY_LEVELS.HIGH,
    status: COMPLAINT_STATUSES.PENDING,
    assignedTo: null,
    cameraNumber: CAMERA_NAMES[2],
    createdAt: new Date('2026-06-24T09:45:00'),
  },
  {
    id: 'C003',
    date: '2026-06-24',
    time: '10:20 AM',
    location: LOCATIONS[2],
    issueType: ISSUE_TYPES.ENVIRONMENTAL_CONCERN,
    description: 'Bird activity near terminal',
    severity: SEVERITY_LEVELS.MEDIUM,
    status: COMPLAINT_STATUSES.PENDING,
    assignedTo: null,
    cameraNumber: CAMERA_NAMES[4],
    createdAt: new Date('2026-06-24T10:20:00'),
  },

  // Active/Informed complaints (assigned)
  {
    id: 'C004',
    date: '2026-06-24',
    time: '08:30 AM',
    location: LOCATIONS[0],
    issueType: ISSUE_TYPES.MAINTENANCE_REQUIRED,
    description: 'Runway lighting system malfunction',
    severity: SEVERITY_LEVELS.HIGH,
    status: COMPLAINT_STATUSES.ACTIVE,
    assignedTo: OFFICERS[0],
    cameraNumber: CAMERA_NAMES[1],
    createdAt: new Date('2026-06-24T08:30:00'),
  },
  {
    id: 'C005',
    date: '2026-06-24',
    time: '08:15 AM',
    location: LOCATIONS[3],
    issueType: ISSUE_TYPES.SECURITY_ISSUE,
    description: 'Unauthorized person in restricted area',
    severity: SEVERITY_LEVELS.CRITICAL,
    status: COMPLAINT_STATUSES.INFORMED,
    assignedTo: OFFICERS[1],
    cameraNumber: CAMERA_NAMES[7],
    createdAt: new Date('2026-06-24T08:15:00'),
  },
  {
    id: 'C006',
    date: '2026-06-24',
    time: '07:45 AM',
    location: LOCATIONS[1],
    issueType: ISSUE_TYPES.EQUIPMENT_MALFUNCTION,
    description: 'Taxiway sign illumination issue',
    severity: SEVERITY_LEVELS.MEDIUM,
    status: COMPLAINT_STATUSES.ACTIVE,
    assignedTo: OFFICERS[2],
    cameraNumber: CAMERA_NAMES[3],
    createdAt: new Date('2026-06-24T07:45:00'),
  },
  {
    id: 'C007',
    date: '2026-06-24',
    time: '07:20 AM',
    location: LOCATIONS[2],
    issueType: ISSUE_TYPES.MAINTENANCE_REQUIRED,
    description: 'Jet bridge mechanical failure',
    severity: SEVERITY_LEVELS.HIGH,
    status: COMPLAINT_STATUSES.INFORMED,
    assignedTo: OFFICERS[3],
    cameraNumber: CAMERA_NAMES[5],
    createdAt: new Date('2026-06-24T07:20:00'),
  },
  {
    id: 'C008',
    date: '2026-06-24',
    time: '06:50 AM',
    location: LOCATIONS[3],
    issueType: ISSUE_TYPES.OTHER,
    description: 'Baggage handling system delay',
    severity: SEVERITY_LEVELS.LOW,
    status: COMPLAINT_STATUSES.ACTIVE,
    assignedTo: OFFICERS[4],
    cameraNumber: CAMERA_NAMES[6],
    createdAt: new Date('2026-06-24T06:50:00'),
  },

  // Closed complaints
  {
    id: 'C009',
    date: '2026-06-23',
    time: '05:30 PM',
    location: LOCATIONS[0],
    issueType: ISSUE_TYPES.ENVIRONMENTAL_CONCERN,
    description: 'Noise complaint from nearby residents',
    severity: SEVERITY_LEVELS.LOW,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[5],
    cameraNumber: CAMERA_NAMES[0],
    createdAt: new Date('2026-06-23T17:30:00'),
  },
  {
    id: 'C010',
    date: '2026-06-23',
    time: '04:15 PM',
    location: LOCATIONS[2],
    issueType: ISSUE_TYPES.EQUIPMENT_MALFUNCTION,
    description: 'Scanner malfunction at security checkpoint',
    severity: SEVERITY_LEVELS.MEDIUM,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[0],
    cameraNumber: CAMERA_NAMES[4],
    createdAt: new Date('2026-06-23T16:15:00'),
  },
  {
    id: 'C011',
    date: '2026-06-23',
    time: '02:45 PM',
    location: LOCATIONS[1],
    issueType: ISSUE_TYPES.SAFETY_HAZARD,
    description: 'Wet floor hazard in terminal',
    severity: SEVERITY_LEVELS.MEDIUM,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[1],
    cameraNumber: CAMERA_NAMES[3],
    createdAt: new Date('2026-06-23T14:45:00'),
  },
  {
    id: 'C012',
    date: '2026-06-23',
    time: '01:20 PM',
    location: LOCATIONS[3],
    issueType: ISSUE_TYPES.MAINTENANCE_REQUIRED,
    description: 'Air conditioning system repair needed',
    severity: SEVERITY_LEVELS.LOW,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[2],
    cameraNumber: CAMERA_NAMES[7],
    createdAt: new Date('2026-06-23T13:20:00'),
  },
  {
    id: 'C013',
    date: '2026-06-23',
    time: '11:00 AM',
    location: LOCATIONS[0],
    issueType: ISSUE_TYPES.SECURITY_ISSUE,
    description: 'Lost and found item suspected package',
    severity: SEVERITY_LEVELS.HIGH,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[3],
    cameraNumber: CAMERA_NAMES[1],
    createdAt: new Date('2026-06-23T11:00:00'),
  },
  {
    id: 'C014',
    date: '2026-06-23',
    time: '09:30 AM',
    location: LOCATIONS[2],
    issueType: ISSUE_TYPES.OTHER,
    description: 'Customer complaint about wait times',
    severity: SEVERITY_LEVELS.LOW,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[4],
    cameraNumber: CAMERA_NAMES[5],
    createdAt: new Date('2026-06-23T09:30:00'),
  },
  {
    id: 'C015',
    date: '2026-06-23',
    time: '08:00 AM',
    location: LOCATIONS[1],
    issueType: ISSUE_TYPES.EQUIPMENT_MALFUNCTION,
    description: 'Conveyor belt jammed',
    severity: SEVERITY_LEVELS.MEDIUM,
    status: COMPLAINT_STATUSES.CLOSED,
    assignedTo: OFFICERS[5],
    cameraNumber: CAMERA_NAMES[2],
    createdAt: new Date('2026-06-23T08:00:00'),
  },
];

export const SEVERITY_COLORS = {
  critical: 'bg-red-600 text-white',
  high: 'bg-orange-500 text-white',
  medium: 'bg-amber-400 text-black',
  low: 'bg-blue-500 text-white',
};

export const STATUS_COLORS = {
  pending: 'bg-gray-400 text-white',
  active: 'bg-blue-600 text-white',
  informed: 'bg-purple-600 text-white',
  closed: 'bg-green-600 text-white',
};

export const STATUS_LABELS = {
  pending: 'Pending',
  active: 'Active',
  informed: 'Informed',
  closed: 'Closed',
};
